-- MySQL Script generated by MySQL Workbench
-- Mon May  1 18:40:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema resenha_de_filme
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `resenha_de_filme` ;

-- -----------------------------------------------------
-- Schema resenha_de_filme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resenha_de_filme` DEFAULT CHARACTER SET utf8 ;
USE `resenha_de_filme` ;

-- -----------------------------------------------------
-- Table `resenha_de_filme`.`genero_usu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`genero_usu` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`genero_usu` (
  `id_genero_usu` INT NOT NULL AUTO_INCREMENT,
  `genero_usu` ENUM('masculino', 'feminino','naoBinario','naoDeclarar') NOT NULL COMMENT 'masculino, feminino, naoBinario, naoDeclarar',
  PRIMARY KEY (`id_genero_usu`))
ENGINE = InnoDB;

--
-- Despejando dados para a tabela `genero_usu`
--

INSERT INTO `genero_usu` (`id_genero_usu`, `genero_usu`) VALUES
(1, 'masculino'),(2, 'feminino'),(3, 'naoBinario'),(4, 'naoDeclarar');


-- -----------------------------------------------------
-- Table `resenha_de_filme`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`usuario` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usu` VARCHAR(100) NOT NULL,
  `nickname_usu` VARCHAR(100) NOT NULL,
  `dt_de_nasci_usu` DATE NULL DEFAULT NULL,
  `email_usu` VARCHAR(100) NOT NULL,
  `senha_usu` VARCHAR(60) NOT NULL,
  `situacao_usu` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Ativo, Inativo ou Bloqueado\n',
  `perfil_usu` VARCHAR(15) NULL DEFAULT 'usuario' COMMENT 'usuario, administrador, moderador',
  `foto_usu` VARCHAR(500) NULL DEFAULT NULL,
  `fk_genero_usu_id_genero_usu` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `fk_genero_usu_id_genero_usu`),
  INDEX `fk_usuario_genero_usu1_idx` (`fk_genero_usu_id_genero_usu` ASC) ,
  CONSTRAINT `fk_usuario_genero_usu1`
    FOREIGN KEY (`fk_genero_usu_id_genero_usu`)
    REFERENCES `resenha_de_filme`.`genero_usu` (`id_genero_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resenha_de_filme`.`genero_filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`genero_filme` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`genero_filme` (
  `id_genero_filme` INT NOT NULL AUTO_INCREMENT,
  `genero_filme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero_filme`))
ENGINE = InnoDB;


--
-- Despejando dados para a tabela `genero_filme`
--

INSERT INTO `genero_filme` (`id_genero_filme`, `genero_filme`) VALUES
(1, 'infantil'),(2, 'romance'),(3, 'acao'),(4, 'dorama'),(5, 'ficcao'),(6, 'terror'),(7, 'comedia'),(8, 'drama'),(9, 'faroeste'),(10, 'suspense');


-- -----------------------------------------------------
-- Table `resenha_de_filme`.`canal_filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`canal_filme` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`canal_filme` (
  `id_canal_filme` INT NOT NULL AUTO_INCREMENT,
  `canal_filme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_canal_filme`))
ENGINE = InnoDB;


--
-- Despejando dados para a tabela `canal_filme`
--

INSERT INTO `canal_filme` (`id_canal_filme`, `canal_filme`) VALUES
(1, 'infantil'),(2, 'romance'),(3, 'acao'),(4, 'dorama'),(5, 'ficcao'),(6, 'terror'),(7, 'comedia'),(8, 'drama'),(9, 'faroeste'),(10, 'suspense');

-- -----------------------------------------------------
-- Table `resenha_de_filme`.`filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`filme` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`filme` (
  `id_filme` INT NOT NULL AUTO_INCREMENT,
  `nome_filme` VARCHAR(80) NOT NULL,
  `dt_de_lancamento_filme` DATE NULL DEFAULT NULL,
  `duracao_filme` TIME NULL DEFAULT NULL,
  `sinopse_filme` VARCHAR(250) NOT NULL,
  `classificacao_filme` VARCHAR(50) NOT NULL,
  `capa_filme` VARCHAR(50) NOT NULL,
  `trailer_filme` VARCHAR(50) NULL DEFAULT NULL,
  `fk_usuario_id_usuario` INT NOT NULL,
  `fk_genero_filme_id_genero_filme` INT NOT NULL,
  `fk_canal_filme_id_canal_filme` INT NOT NULL,
  PRIMARY KEY (`id_filme`, `fk_usuario_id_usuario`, `fk_genero_filme_id_genero_filme`, `fk_canal_filme_id_canal_filme`),
  INDEX `fk_filme_usuario1_idx` (`fk_usuario_id_usuario` ASC),
  INDEX `fk_filme_genero_filme1_idx` (`fk_genero_filme_id_genero_filme` ASC) ,
  INDEX `fk_filme_canal_filme1_idx` (`fk_canal_filme_id_canal_filme` ASC) ,
  CONSTRAINT `fk_filme_usuario1`
    FOREIGN KEY (`fk_usuario_id_usuario`)
    REFERENCES `resenha_de_filme`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_genero_filme1`
    FOREIGN KEY (`fk_genero_filme_id_genero_filme`)
    REFERENCES `resenha_de_filme`.`genero_filme` (`id_genero_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_canal_filme1`
    FOREIGN KEY (`fk_canal_filme_id_canal_filme`)
    REFERENCES `resenha_de_filme`.`canal_filme` (`id_canal_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `resenha_de_filme`.`favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`favorito` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`favorito` (
  `id_favorito` INT NOT NULL AUTO_INCREMENT,
  `favorito` TINYINT(2) NULL DEFAULT NULL COMMENT 'inativo\nativo',
  `fk_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_favorito`, `fk_usuario_id_usuario`),
  INDEX `fk_favorito_usuario1_idx` (`fk_usuario_id_usuario` ASC) ,
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`fk_usuario_id_usuario`)
    REFERENCES `resenha_de_filme`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resenha_de_filme`.`resenha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`resenha` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`resenha` (
  `id_resenha` INT NOT NULL AUTO_INCREMENT,
  `avaliacao_res` VARCHAR(50) NULL DEFAULT NULL,
  `descricao_res` VARCHAR(1500) NULL DEFAULT NULL,
  `dt_hora_res` TIMESTAMP NULL DEFAULT NULL,
  `denuncia_res` VARCHAR(50) NULL DEFAULT NULL,
  `situacao_res` VARCHAR(50) NULL DEFAULT NULL COMMENT 'ativo, inativo ou bloqueado\n',
  `fk_filme_id_filme` INT NOT NULL,
  `fk_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_resenha`, `fk_filme_id_filme`, `fk_usuario_id_usuario`),
  INDEX `fk_resenha_filme1_idx` (`fk_filme_id_filme` ASC) ,
  INDEX `fk_resenha_usuario1_idx` (`fk_usuario_id_usuario` ASC) ,
  CONSTRAINT `fk_resenha_filme1`
    FOREIGN KEY (`fk_filme_id_filme`)
    REFERENCES `resenha_de_filme`.`filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resenha_usuario1`
    FOREIGN KEY (`fk_usuario_id_usuario`)
    REFERENCES `resenha_de_filme`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resenha_de_filme`.`filme_has_favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resenha_de_filme`.`filme_has_favorito` ;

CREATE TABLE IF NOT EXISTS `resenha_de_filme`.`filme_has_favorito` (
  `fk_filme_id_filme` INT NOT NULL,
  `fk_favorito_id_favorito` INT NOT NULL,
  `fk_favorito_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`fk_filme_id_filme`, `fk_favorito_id_favorito`, `fk_favorito_usuario_id_usuario`),
  INDEX `fk_filme_has_favorito_favorito1_idx` (`fk_favorito_id_favorito` ASC, `fk_favorito_usuario_id_usuario` ASC) ,
  INDEX `fk_filme_has_favorito_filme1_idx` (`fk_filme_id_filme` ASC) ,
  CONSTRAINT `fk_filme_has_favorito_filme1`
    FOREIGN KEY (`fk_filme_id_filme`)
    REFERENCES `resenha_de_filme`.`filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_favorito_favorito1`
    FOREIGN KEY (`fk_favorito_id_favorito` , `fk_favorito_usuario_id_usuario`)
    REFERENCES `resenha_de_filme`.`favorito` (`id_favorito` , `fk_usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;